# http server的端口
server:
  port: 8016

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 50
  jackson:
    #返回json首字母小写
    property-naming-strategy: LOWER_CAMEL_CASE
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        #监控统计拦截的filters
        filters: stat,log4j
        #配置初始化大小/最小/最大
        initial-size: 2
        min-idle: 2
        max-active: 5
        #获取连接等待超时时间(毫秒)
        max-wait: -1
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        keepAlive: false
        min-evictable-idle-time-millis: 1800000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        #        pool-prepared-statements: false
        #        max-pool-prepared-statement-per-connection-size: 300
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 10000
      primary: mysqlMaster
      lazy: false #默认立即初始化数据源，true则支持在需要建立连接时再初始化数据源
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源
      datasource:
        mysqlMaster:
#          url: jdbc:mysql://192.168.101.152:3306/wx-rcgy?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          url: jdbc:p6spy:mysql://192.168.101.152:3306/wx-rcgy?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: swsk@swsk123456
#          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          druid: # 以下参数针对每个库可以重新设置druid参数
            validation-query: select 1  #比如mysql就需要重新设置这个